;; Gripper domain with types
(define (domain gripper-typed)
  (:requirements :typing)
  (:types ball - grippable room gripper)
  (:predicates (at_robby ?r - room) (at ?b - ball ?r - room)
               (free ?g - gripper) (carry ?o - ball ?g - gripper))
  (:action move
   :parameters (?from - room ?to - room)
   :precondition (at_robby ?from)
   :effect (and (at_robby ?to)
                (not (at_robby ?from))))
  (:action pick
   :parameters (?obj - grippable ?room - room ?gripper - gripper)
   :precondition (and (at ?obj ?room)
                      (at_robby ?room)
                      (free ?gripper))
   :effect (and (carry ?obj ?gripper)
                (not (at ?obj ?room))
                (not (free ?gripper))))
  (:action drop
   :parameters (?obj - grippable ?room - room ?gripper - gripper)
   :precondition (and (carry ?obj ?gripper)
                      (at_robby ?room))
   :effect (and (at ?obj ?room)
                (free ?gripper)
                (not (carry ?obj ?gripper)))))
