(define (problem ball-throw-problem)
    (:domain ball-throw)
    (:objects ball1 ball2)
    (:init (on-floor ball1)
           (on-floor ball2)
           (= (loc ball1) 0)
           (= (loc ball2) 0)
           (= (wall-height) 5)
           (= (wall-dist) 5)
           (= (throw-speed) 20))
    (:goal (and (< (loc ball1) 10)
                (> (loc ball2) 15)))
)
