(define (problem ball-throw-problem)
    (:domain ball-throw)
    (:objects ball1 ball2)
    (:init (on-floor ball1)
           (on-floor ball2)
           (= (loc ball1) 0.0)
           (= (loc ball2) 0.0)
           (= (wall-height) 5.0)
           (= (wall-dist) 5.0)
           (= (throw-speed) 20.0))
    (:goal (and (< (loc ball1) 10.0)
                (> (loc ball2) 15.0)))
)
